### PR TITLE
Added New Digital Clock

### PR DESCRIPTION
**Pull request by prathamesh-borse**
Added New Digital Clock Created by @prathamesh-borse 👍 

Review it and if it is mine then merge it with our Repository.!

### CODE REVIEW

**Review by kamleshjoshi8102 — CHANGES_REQUESTED** [review]
Can You modify the Existing Project with Date and Day?

**Comment by prathamesh-borse** [comment]
What I have to change?

**Comment by adityamangal1** [comment]
Not any change, Just try to make changes or beautify the existing clock in this repo

**Comment by prathamesh-borse** [comment]
> Just try to make changes or beautify the existing clock in this repo

Okay.

**Comment by prathamesh-borse** [comment]
@kamleshjoshi8102 Should I Close This Pull Request Now.? or You Are Going To Merge it.!🙌

**Comment by harikanani** [comment]
@prathamesh-borse You should close this issue by now as it's merged and resolved.

Thank you for your valuable contribution 😊

**Comment by prathamesh-borse** [comment]
> @prathamesh-borse You should close this issue by now as it's merged and resolved.
> 
> Thank you for your valuable contribution 😊

Closed Pull Request and One More Thing @harikanani, @kamleshjoshi8102 has assigned Me A Task to add Day in the existing clock so I Am Making A New PR For that Please Review Nd Do let Me Know On Tommorow 🙌👍

**Pull request closed without merging**
