### PR TITLE
added multiple time zones

### PR DESCRIPTION
**Pull request by rishigupta1109**
issue #2

### CODE REVIEW

**Review by kevalvavaliya — APPROVED** [review]
LGTM

**Review by kamleshjoshi8102 — CHANGES_REQUESTED** [review]
hey Can you resolve Conflicts : )

**Review by kevalvavaliya — COMMENTED** [review]
@rishigupta1109 can you please share the snapshot of project?

**Comment by rishigupta1109** [comment]
sure

**Comment by rishigupta1109** [comment]
dcss1
dcss2
dcss3

**Review by kevalvavaliya — APPROVED** [review]
Looks good thanks for your contribution ⚡

**Review by Nitesh-thapliyal — APPROVED** [review]

**Review by kamleshjoshi8102 — APPROVED** [review]
LGTM ✅✅

**Pull request merged**
