### PR TITLE
Improved Existing Clock

### PR DESCRIPTION
**Pull request by prathamesh-borse**
@adityamangal1 Please Review it and let me  #know.! and if possible close this Pull Request if you want #1 
- Improved Existing Clock
   -  Added Different Border Style 
   - Improved Some Padding and Margin
   - Shifted Clock to the center of the Screen

### CODE REVIEW

**Review by kamleshjoshi8102 — APPROVED** [review]

**Comment by prathamesh-borse** [comment]
Hey, @kamleshjoshi8102 can u Please Label this Pull Request Has Hacktoberfest Accepted so that It will counted on Hacktoberfest.

**Comment by kamleshjoshi8102** [comment]
> Hey, @kamleshjoshi8102 can u Please Label this Pull Request Has Hacktoberfest Accepted so that It will counted on Hacktoberfest.

It was before 1 Oct. so can't be counted : ) 

But you're free to contribute again

**Comment by prathamesh-borse** [comment]
OKAY @kamleshjoshi8102 👍 
Can u Please Guide What are Issues that are available on Bauddhik-Geeks.

**Comment by kamleshjoshi8102** [comment]
> OKAY @kamleshjoshi8102 👍 Can u Please Guide What are Issues that are available on Bauddhik-Geeks.

We have many beginner-friendly projects too :) You can create new issues in them or work in existing issues: )

**Pull request merged**
